# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build & test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/chaser-design-system/
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: latest

      - name: Set node version to 22
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install
        run: pnpm i

      - name: Install Playwright Dependencies
        run: pnpm i playwright && pnpm exec playwright install chromium --with-deps

      - name: Test
        run: pnpm run test
